# Generated by Django 4.1.7 on 2023-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lic', models.CharField(max_length=20)),
                ('num_sap', models.CharField(max_length=15)),
                ('objeto', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Controle TES',
            },
        ),
    ]
