# Generated by Django 4.1.7 on 2023-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lic', models.CharField(max_length=20)),
                ('num_sap', models.CharField(max_length=15)),
                ('objeto', models.CharField(max_length=300)),
                ('historico', models.CharField(blank=True, max_length=300)),
                ('resp_pac', models.CharField(max_length=30)),
                ('an_lic', models.CharField(max_length=30)),
                ('area_req', models.CharField(max_length=10)),
                ('crit_julg', models.CharField(max_length=10)),
                ('mod_contr', models.CharField(max_length=10)),
                ('proc_ele', models.BooleanField(default=False)),
                ('data_i0', models.DateField()),
                ('disputa', models.CharField(max_length=20)),
                ('fonte_rec', models.CharField(max_length=20)),
                ('orcado', models.CharField(max_length=25)),
                ('valor_contr', models.CharField(blank=True, max_length=25)),
                ('vencedora', models.CharField(blank=True, max_length=25)),
                ('comissao', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Controle TE',
            },
        ),
    ]
